package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"chatspace-server/graph/model"
	"context"
)

// CreateSpace is the resolver for the createSpace field.
func (r *mutationResolver) CreateSpace(ctx context.Context, request model.SpaceRequest) (*model.Space, error) {
	return r.ucSpace.CreateSpace(ctx, request)
}

// JoinSpace is the resolver for the joinSpace field.
func (r *mutationResolver) JoinSpace(ctx context.Context, spaceID string) (*model.Space, error) {
	return r.ucSpace.JoinSpace(ctx, spaceID)
}

// Spaces is the resolver for the spaces field.
func (r *queryResolver) Spaces(ctx context.Context) ([]*model.Space, error) {
	return r.ucSpace.Spaces(ctx)
}

// Space is the resolver for the space field.
func (r *queryResolver) Space(ctx context.Context, id string) (*model.Space, error) {
	return r.ucSpace.Space(ctx, id)
}
