package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"hora-server/graph/generated"
	"hora-server/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, request model.RegisterRequest) (*model.AuthResponse, error) {
	return r.ucUser.Register(ctx, request)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, request model.LoginRequest) (*model.AuthResponse, error) {
	return r.ucUser.Login(ctx, request)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, request model.RefreshRequest) (*model.AuthResponse, error) {
	return r.ucUser.RefreshToken(ctx, request)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	return r.ucUser.User(ctx)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
