// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	Token        string  `json:"token"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Message struct {
	ID        string    `json:"id"`
	Content   string    `json:"content"`
	User      *User     `json:"user"`
	Space     *Space    `json:"space"`
	CreatedAt time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Space struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	Members     []*User    `json:"members"`
	Admins      []*User    `json:"admins"`
	Messages    []*Message `json:"Messages"`
}

type SpaceRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Subscription struct {
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Password  string `json:"password"`
	UpdatedAt string `json:"updatedAt"`
	CreatedAt string `json:"createdAt"`
}
